language: ruby
branches:
  only:
  - master
rvm:
- 2.0.0
- 1.9.3
- rbx-19mode
env:
  global:
  - secure: wRDLGbg+GS7Eo6KhjyAA6YNm6rFVo8j53b0oEZLBkJ2VzvLsKMnpEfopzc0W2wttgVwgkX8C/9adbd/BPsEYbpO+uJFt5DX3A2HVVXCZ2jP0TgLj2m4dOA4ohroYDcdeB0fuZM7a7hvFNswd9vSRLmes6vLQ0GcFTSz1rWQLf6U=
  - secure: e7We+H6/XlWrPVSlLNcXdQxSC520SP2BteSddBjD9YNx9DosMDLTi85Rw3KJGRQowoftv00TwAe+iCRTyPElrW0Q/y5ozAU9UyipAtwhZhM06IPx1fhkU/Q3FIX/iwgruS253aiGlIUg7YcdGwfYuURk2iu7Xp3OdhS/evxbj/E=
